#' Run a Kruskal-Wallis One-Way ANOVA on non-parametric data at the isoform level for a selected gene
#'
#' @param sleuth_obj An existing Sleuth object as generated by sleuth_prep() and fit by sleuth_fit()
#' @param gene The name of a gene as a string to asses the isoform expression level between samples
#' @param sample_suffix_range An integer indicating the maximum suffix of biological replicates that will be collappsed upon
#'
#' @return Results of a kruskal-wallis test at the isoform level and the pairwise wilcox test to identify the potentially signficantly different isoforms and the mean results.
#' @export
#' @examples
#' # Given a Sleuth object, run the kruskal-wallis test of the tpm factor between isoform groups for all samples.
#' sleuth_kruskal_wallis(so_nominal, "ABH1", 3)
sleuth_kruskal_wallis <- function(sleuth_obj, gene, sample_suffix_range, isoform_plot = FALSE){
  kw_result <- sleuth_obj$obs_norm_filt %>% mutate(est_counts = est_counts*sleuth_obj$est_counts_sf)
  foo_trans <- filter(sleuth_obj$target_mapping, ext_gene == gene)
  kw_result <- kw_result[kw_result$target_id %in% foo_trans$target_id,]
  kw_result <- right_join(foo_trans, kw_result, by = "target_id")
  
  for (num in range(1:sample_suffix_range)) {
    kw_result$sample <- gsub(paste("_", num, sep=""), "", kw_result$sample)
  }
  
  kw_result_mean <- group_by(kw_result, target_id, sample) %>% summarise(mean(est_counts), mean(tpm), mean(eff_len), mean(len))
  colnames(kw_result_mean) <- c("target_id", "sample", "est_counts", "tpm", "eff_len", "len")
  
  assign("kw_result_mean", kw_result_mean, envir = .GlobalEnv)
  
  if (dim(kw_result_mean)[1] == 0) {
    cat("Check that the gene exists in the dataset.")
  }
  
  kw_stat <- kruskal.test(tpm ~ target_id, data = kw_result_mean)
  print(kw_stat)
  
  pw_w_Stat <- pairwise.wilcox.test(kw_result_mean$tpm, kw_result_mean$target_id, p.adjust.method = "BH")
  print(pw_w_Stat)
  
  return(kw_result_mean)
}


