#' Generate a multidimensional PCA plot with independent loading plots.
#'
#' @param object An existing Seurat object.
#' @param ggPlotList The output graph generated by plotReducedDim.
#' @param nloadings A numeric value for the number of loadings to showcase on single loading plot.
#' @param loadingScaleFactor A numeric value to scale the loading vectors by.
#'
#' @export
#' @examples
#' # Create a multidimensional PCA plot with independent loading plots
#' prd_obj <- plotReducedDim(sce_object, dimred = "PCA", colour_by = "seurat_clusters", ncomponents = 3)
#' plotFromReducedDim(seu_object, prd_obj, nloadings = 5, loadingScaleFactor = 100)
plotFromReducedDim <- function(seu_object = NULL, ggPlotList = NULL,
                              nloadings = 5, loadingScaleFactor = 150) {
  # Check the inputs are the correct class
  if (class(seu_object)[1] != "Seurat"){
    object_class <- class(sce_object)[1]
    return(paste("SingleCellExperiment Object being passed is not the correct class of SingleCellExperiment, but instead:", object_class))
  }
  if (class(ggPlotList)[1] != "gg"){
    ggPlotList_class <- class(ggPlotList)[1]
    return(paste("ggPlot Object being passed is not the correct class of gg, but instead:", ggPlotList_class))
  }
  
  # Check that a multidimensional plot can be generated
  plot_out <- ggPlotList
  if (length(plot_out$layers) <= 1){
    return("The graph provided is 2-dimensional. Cannot showcase a multidimensional loading plot.")
  }
  
  # Modify the data for the scatter plot and remove the top right
  plotD1 <- ggPlotList$data
  pcaComponents <- levels(ggPlotList$data$xvar)
  pcaNumComponents <- length(pcaComponents)
  for (xvar in pcaComponents){
    for (yvar in pcaComponents[-1]){
      # Check that the diagonal values are not being removed
      if (xvar != yvar){
        # Check that only the upper right side is being removed
        if (strsplit(xvar, " ")[[1]][2] < strsplit(yvar, " ")[[1]][2]){
          plotD1 <- plotD1[!(plotD1$xvar == xvar & plotD1$yvar == yvar),]
        }
      }
    }
  }
  
  # Assign the top right removed data to the ggPlot object
  plot_out$layers[[2]]$data <- plotD1
  
  # Subset the existing Seurat PCA to the number of axes used when running
  # the plotReducedDim function
  pca_loadings <- seu_object@reductions$pca@feature.loadings
  pca_loadings <- pca_loadings[,1:pcaNumComponents]
  
  # Calculate the vector magnitude for each PC combination to plot
  combs <- combn(ncol(pca_loadings), 2)
  pca_loading_vector_length_df <- do.call(rbind, lapply(1:ncol(combs), function(y) {
    sub_df <- pca_loadings[, combs[, y]]
    total <- rowSums(sub_df ^ 2)
    temp_df <- data.frame(
      xvar = colnames(sub_df)[1], 
      yvar = colnames(sub_df)[2], 
      xend = sub_df[, 1], 
      yend = sub_df[, 2], 
      total = total
    )
    temp_df <- temp_df[order(total, decreasing = TRUE),][1:nloadings, ]
    temp_df$rownames <- rownames(temp_df)
    return(temp_df)
  }))
  
  # Switch the PC_N notation to "PCA N", where N is a number
  pca_loading_vector_length_df$xvar <- gsub("C", "CA ", pca_loading_vector_length_df$xvar)
  pca_loading_vector_length_df$yvar <- gsub("C", "CA ", pca_loading_vector_length_df$yvar)
  pca_loading_vector_length_df$xvar <- gsub("_", "", pca_loading_vector_length_df$xvar)
  pca_loading_vector_length_df$yvar <- gsub("_", "", pca_loading_vector_length_df$yvar)
  
  assign("loading_vectors", pca_loading_vector_length_df, envir = .GlobalEnv)
  
  # Scale the loading vectors by a user provided value
  pca_loading_vector_length_df$xend <- (pca_loading_vector_length_df$xend * loadingScaleFactor)
  pca_loading_vector_length_df$yend <- (pca_loading_vector_length_df$yend * loadingScaleFactor)
  
  # Plot the graph
  plot_out <- plot_out + geom_segment(data=pca_loading_vector_length_df, 
                                      aes(x = 0, y = 0, xend = xend, yend = yend),
                                      inherit.aes = FALSE) + 
    geom_text_repel(data = pca_loading_vector_length_df, 
                    aes(x = xend, y = yend, label = rownames), 
                    inherit.aes = FALSE, segment.color = "transparent", 
                    size = 2, force = 2)
  
  plot_out
}

#' Generate N number of piecharts, where N is the number of factor levels of the seurat clusters or a unique metadata feature.
#'
#' @param object An existing Seurat object.
#' @param meta_feature The metadata feature that is highlighted when plotting clusters.
#' @param plot_by Character string of either 'clusters' or 'meta_feature', denoting what to split by.
#' @param facet Boolean value to denote if the plot should have facet_wrap applied.
#' @param label_by Character string, either "counts" or "percent"
#' @param include_labels Boolean value to denote if the plot should have labels for each slice.
#'
#' @export
#' @examples
#' # Create a pie chart with labels and apply facet_wrap with custom parameters after
#' plot <- cluster_identities(object = seurat_object, meta_feature = "collection.date", plot_by = 'clusters', facet = FALSE, include_labels = TRUE)
#' plot + facet_wrap(~ combined)
cluster_identities <- function(object, meta_feature, plot_by = 'clusters', 
                               facet = TRUE, include_labels = TRUE, label_by = "counts") {
  # Check that the metadata feature is present in the object.
  if (!(meta_feature %in% colnames(object@meta.data))){
    return("Chosen metadata feature cannot be found in the seurat object provided.")
  }
  # Check that the plotting selection is correct.
  if (!(plot_by == 'clusters' | plot_by == 'meta_feature')){
    return("Incorrect plot_by variables.")
  }
  
  object_metadata <- object@meta.data
  
  # Get the column index for the feature selected and factorize the column
  metadata_col <- grep(meta_feature, colnames(object_metadata))
  object_metadata[,metadata_col] <- factor(object_metadata[,metadata_col])
  
  # Rename the numeric clusters to "Cluster N", where N is the original numeric value
  object_metadata$seurat_clusters <- paste("Cluster ", object_metadata$seurat_clusters)
  
  object_metadata <- object_metadata %>%
    group_by(across(all_of(c("seurat_clusters", meta_feature)))) %>%
    summarise(count = n()) %>%
    mutate(percent_per_cluster = count / sum(count),
           total_per_cluster = sum(count)) %>%
    group_by(across(all_of(meta_feature))) %>%
    mutate(percent_per_meta = count / sum(count),
           total_per_meta = sum(count)) %>%
    ungroup()
  
  # Generate a ggplot with n number of pie charts, where n is the number of seurat clusters factors
  if (plot_by == 'clusters'){
    object_metadata$combined <- do.call(paste, c(object_metadata[c(1,5)], sep = "\nTotal Cells = "))
    
    # Define the y-value for the label plot locations and rename the labelling column
    label_locations <- object_metadata %>% 
      group_by(across(all_of("seurat_clusters"))) %>%
      mutate(cs = rev(cumsum(rev(percent_per_cluster))), 
             pos = percent_per_cluster / 2 + lead(cs, 1), 
             pos = if_else(is.na(pos), percent_per_cluster /  2, pos))
    label_locations$percent_per_cluster <- paste(round(label_locations$percent_per_cluster * 100, 2), '%', sep='')
    
    if (label_by == "counts"){
      colnames(label_locations)[3] <- 'label' 
    }
    else if (label_by == "percent"){
      colnames(label_locations)[4] <- 'label'
    }
    
    # Here, we use aes_string because the fill is being passed in programmatically.
    out_plot <- ggplot(data = object_metadata, 
                       aes_string(x = factor(1), y = "percent_per_cluster", fill = meta_feature)) +
      geom_bar(stat = "identity", position = position_fill(), width = 1, color = "white") +
      coord_polar("y", start = 0) +
      theme_void() + 
      theme(strip.text.x = element_text(face = "bold")) 
  }
  
  # Generate a ggplot with n number of pie charts, where n is the number of metadata_feature factors
  else if (plot_by == 'meta_feature'){
    object_metadata$combined <- do.call(paste, c(object_metadata[c(2,7)], sep = "\nTotal Cells = "))
    
    # Define the y-value for the label plot locations and rename the labelling column
    label_locations <- object_metadata %>% 
      group_by(across(all_of(meta_feature))) %>%
      mutate(cs = rev(cumsum(rev(percent_per_meta))), 
             pos = percent_per_meta / 2 + lead(cs, 1), 
             pos = if_else(is.na(pos), percent_per_meta /  2, pos))
    label_locations$percent_per_meta <- paste(round(label_locations$percent_per_meta * 100, 2), '%', sep='')
    
    assign("feature_meta", object_metadata, envir = .GlobalEnv)
    assign("lab", label_locations, envir = .GlobalEnv)
    
    if (label_by == "counts"){
      colnames(label_locations)[5] <- 'label'
    }
    else if (label_by == "percent"){
      colnames(label_locations)[6] <- 'label' 
    }
    
    out_plot <- ggplot(data = object_metadata, 
                       aes(x = factor(1), y = percent_per_meta, fill = seurat_clusters)) + 
      geom_bar(stat = "identity", position = position_fill(), width = 1, color = "white") +
      coord_polar("y", start = 0) +
      theme_void() + 
      theme(strip.text.x = element_text(face = "bold"))
  }
  
  if (facet && include_labels){  
    out_plot <- out_plot + 
      geom_text_repel(data = label_locations, aes(y = pos, label = label), 
                      force = 1, nudge_x = 1, min.segment.length = 0) + 
      facet_wrap(~ combined)
  }
  else if (facet){
    out_plot <- out_plot + facet_wrap(~ combined)
  }
  else if (include_labels){
    out_plot <- out_plot + 
      geom_text_repel(data = label_locations, aes(y = pos, label = label), 
                      force = 1, nudge_x = 1, min.segment.length = 0)
  }
  
  out_plot
}
